GET http://localhost:5000/isconnected

###
POST http://localhost:5000/read
Content-Type: application/json

{
    "q1": [0,1],
    "q2": [10,1]
}

###
POST http://localhost:5000/write
Content-Type: application/json

{
    "q1": [0,[130]],
    "q2": [9,[10]]
}

###
POST http://localhost:5000/write
Content-Type: application/json

{
    "q1": [0,[0,0,0,0,0,0,0,0]],
    "q2": [9,[0,0,0,0,0,0,0,0]]
}

###
POST http://localhost:5000/realtime
Content-Type: application/json

{
    "timestamp": null
}

###
POST http://localhost:5000/set
Content-Type: application/json

{
    "q1": [0,0],
    "q2": [10,2]
}
